# base/kafka-connect/kafka-connect.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect # Kafka Connect 클러스터의 이름
  namespace: efkstack
  annotations:
    # KafkaConnector 리소스를 사용하려면 이 어노테이션이 필요합니다.
    strimzi.io/use-connector-resources: "true" 
spec:
  version: 4.1.0 # Strimzi에서 관리하는 Kafka 버전
  replicas: 1
  bootstrapServers: "b-1.sologmskcluster.81f2k0.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.sologmskcluster.81f2k0.c4.kafka.ap-northeast-2.amazonaws.com:9092"
  #bootstrapServers: a01a893d804ad44018657f3b84eaaa35-1872ea900a3b7e8e.elb.ap-northeast-2.amazonaws.com:9094 # Kafka 클러스터 주소
  # tls:
  #   trustedCertificates:
  #     - secretName: kafka-broker-ca-secret 
  #       certificate: ca.crt
  
  externalConfiguration:
    volumes:
      - name: es-truststore # 볼륨의 논리적 이름
        secret:
          secretName: es-truststore-secret # 마운트할 Kubernetes Secret의 이름

  build:
    output:
      type: docker 
      image: jiwon000/kafka-connect-es:1.0 
      pushSecret: dockerhub-secret 

    plugins:
      - name: kafka-connect-elasticsearch 
        artifacts: 
          - type: zip
            # Confluent Hub에서 제공하는 공식 다운로드 URL을 사용합니다.
            url: https://hub-downloads.confluent.io/api/plugins/confluentinc/kafka-connect-elasticsearch/versions/15.0.1/confluentinc-kafka-connect-elasticsearch-15.0.1.zip
  
  # 2단계에서 설정한 Taint & Toleration 적용
  template:
    pod:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "kafka-connect"
          effect: "NoSchedule"
      
  # Kafka Connect의 기본 설정
  config:
    group.id: my-connect-group
    offset.storage.topic: my_connect_offsets
    config.storage.topic: my_connect_configs
    status.storage.topic: my_connect_statuses
    #security.protocol: SSL
    # ... (기타 CONNECT_ 변수들은 여기에 key: value 형태로 변환)
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: 2
    offset.storage.replication.factor: 2
    status.storage.replication.factor: 2