apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: efkstack
spec:
  version: 8.12.2
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command: ["sh", "-c", "bin/elasticsearch-plugin install --batch repository-s3"]
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: gp3
  # ⬇️ 3. secureSettings 섹션을 추가하여 aws-credentials Secret을 키스토어에 등록합니다.
  secureSettings:
  - secretName: aws-credentials