rules_folder: /opt/elastalert/rules
run_every:
  seconds: 10
buffer_time:
  minutes: 10
es_host: es-cluster-es-http
es_port: 9200
use_ssl: true
verify_certs: false
es_username: elastic
es_password: "${ES_PASSWORD}"
writeback_index: elastalert_status
alert_time_limit:
  days: 2