apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- elastalert-deployment.yaml

configMapGenerator:
- name: elastalert-config
  options:
    disableNameSuffixHash: true  # configmap을 생성할때 뒤에 tag가 붙어서 나오는 것을 방지
  files:
  - config.yaml
  - service_error_rule.yaml
  - system_auth_fail_rule.yaml
  - system_kmsg_error_rule.yaml